version: "2"
networks:
  midhub_dev:
    external: true

services:
  todos-web:
    build: .docker/backend
    restart: on-failure
    container_name: todos-web
    entrypoint: /root/entrypoint.sh
    #command: some params to entrypoint.sh
    env_file:
      - ./.env
    environment:
      - HOT_RELOAD=1
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=docker
    volumes:
      - ".:/src"
    ports:
      - 9090:8080

  todos-nginx:
    build: .docker/nginx
    restart: always
    container_name: todos-nginx
    volumes:
      - ./dist/:/var/www
      - .docker/nginx/certs:/etc/nginx/certs
    ports:
      - 9091:80
    depends_on:
      - todos-web
